var modules =
[
    [ "Dataset", "de/dba/group___dataset.html", null ],
    [ "Filesystem", "da/d3d/group___filesystem.html", null ],
    [ "Format", "de/d08/group___format.html", null ],
    [ "Geo", "d0/d04/group___geo.html", null ],
    [ "Math", "d5/d98/group___math.html", null ],
    [ "Configuration", "d9/d6c/group___configuration.html", null ],
    [ "Misc", "d0/db6/group___misc.html", null ],
    [ "Procedures", "d0/d29/group___procedures.html", null ],
    [ "Stats", "d2/d5a/group___stats.html", null ],
    [ "Structure", "dc/deb/group___structure.html", null ],
    [ "Test", "d8/dd3/group___test.html", null ],
    [ "Integration", "da/d0c/group___integration.html", null ],
    [ "Validation", "d2/d48/group___validation.html", null ],
    [ "Estimation", "d9/d74/group___estimation.html", null ],
    [ "Extraction", "d5/ddc/group___extraction.html", null ],
    [ "Aggregates", "d7/d7b/group___aggregates.html", null ],
    [ "Analysis", "d6/d09/group___analysis.html", null ],
    [ "Anonymisation", "d3/d1d/group___anonymisation.html", null ],
    [ "Upload", "da/d25/group___upload.html", null ],
    [ "Visualisation", "d7/d6f/group___visualisation.html", null ],
    [ "Dissemination", "db/ddb/group___dissemination.html", null ],
    [ "Services", "d0/d70/group___services.html", null ]
];