var searchData=
[
  ['statistical_20operations',['Statistical operations',['../d8/d12/library_stats.html',1,'']]],
  ['structure_20manipulation',['Structure manipulation',['../d7/d51/library_struct.html',1,'']]],
  ['silc_5fds_5fjoin',['silc_ds_join',['../df/db7/sas_ds_compare.html',1,'library_dataset']]],
  ['sas_20quantile',['SAS quantile',['../df/d22/sas_quantile.html',1,'quantile']]],
  ['silc_5fagg_5fcompute',['silc_agg_compute',['../d1/d88/sas_silc_agg_compute.html',1,'Aggregates']]],
  ['silc_5fagg_5fprocess',['silc_agg_process',['../db/d23/sas_silc_agg_process.html',1,'Aggregates']]],
  ['silc_5farope_5fplot_5fvenn',['silc_arope_plot_venn',['../db/d83/sas_silc_arope_plot_venn.html',1,'Visualisation']]],
  ['silc_5fdb_5fexport',['silc_db_export',['../df/ddb/sas_silc_db_export.html',1,'Integration']]],
  ['sas_20silc_5fdb_5flocate',['SAS silc_db_locate',['../de/dfa/sas_silc_db_locate.html',1,'silc_db_locate']]],
  ['silc_5fdb_5fselect',['silc_db_select',['../d8/d8a/sas_silc_db_select.html',1,'Extraction']]],
  ['silc_5fds_5fextract',['silc_ds_extract',['../d1/db0/sas_silc_ds_extract.html',1,'Extraction']]],
  ['silc_5fds_5fsplit',['silc_ds_split',['../df/d5d/sas_silc_ds_split.html',1,'Extraction']]],
  ['silc_5feuvals',['silc_EUvals',['../de/dbf/sas_silc_euvals.html',1,'Aggregates']]],
  ['silc_5fffile_5fexport',['silc_ffile_export',['../de/d2d/sas_silc_ffile_export.html',1,'Upload']]],
  ['silc_5fhsum_5fof_5fpvar',['silc_hsum_of_pvar',['../d0/de5/sas_silc_hsum_of_pvar.html',1,'Estimation']]],
  ['silc_5fincome_5fquantile',['silc_income_quantile',['../d0/da4/sas_silc_income_quantile.html',1,'Estimation']]],
  ['silc_5find_5fbrowse',['silc_ind_browse',['../dd/d0d/sas_silc_ind_browse.html',1,'Estimation']]],
  ['silc_5find_5fcreate',['silc_ind_create',['../d6/dde/sas_silc_ind_create.html',1,'Estimation']]],
  ['silc_5find_5fdeprivation',['silc_ind_deprivation',['../d5/db0/sas_silc_ind_deprivation.html',1,'Estimation']]],
  ['silc_5find_5finfo',['silc_ind_info',['../d1/d74/sas_silc_ind_info.html',1,'Estimation']]],
  ['silc_5find_5ftabulate',['silc_ind_tabulate',['../d9/d2d/sas_silc_ind_tabulate.html',1,'Estimation']]],
  ['silc_5find_5fworking',['silc_ind_working',['../d7/d72/sas_silc_ind_working.html',1,'Estimation']]],
  ['sql_5fclause_5fadd',['sql_clause_add',['../d6/d32/sas_sql_clause_add.html',1,'library_proc']]],
  ['sql_5fclause_5fas',['sql_clause_as',['../d1/d6a/sas_sql_clause_as.html',1,'library_proc']]],
  ['sql_5fclause_5fby',['sql_clause_by',['../d5/d21/sas_sql_clause_by.html',1,'library_proc']]],
  ['sql_5fclause_5fcase',['sql_clause_case',['../d7/dc2/sas_sql_clause_case.html',1,'library_proc']]],
  ['sql_5fclause_5fif',['sql_clause_if',['../d8/da1/sas_sql_clause_if.html',1,'library_proc']]],
  ['sql_5fclause_5fmodify',['sql_clause_modify',['../de/d3e/sas_sql_clause_modify.html',1,'library_proc']]],
  ['sql_5fclause_5fwhere',['sql_clause_where',['../d0/d96/sas_sql_clause_where.html',1,'library_proc']]],
  ['sql_5flist',['sql_list',['../d0/d8e/sas_sql_list.html',1,'library_proc']]],
  ['sql_5foperation_5fany',['sql_operation_any',['../db/db7/sas_sql_operation_any.html',1,'library_proc']]],
  ['sql_5foperation_5fcount',['sql_operation_count',['../d0/de8/sas_sql_operation_count.html',1,'library_proc']]],
  ['sql_5foperation_5fmean',['sql_operation_mean',['../d2/d3a/sas_sql_operation_mean.html',1,'library_proc']]],
  ['sql_5foperation_5fsum',['sql_operation_sum',['../d9/d92/sas_sql_operation_sum.html',1,'library_proc']]],
  ['str_5fdslist',['str_dslist',['../df/d2c/sas_str_dslist.html',1,'library_dataset']]],
  ['str_5fdsname',['str_dsname',['../d3/d46/sas_str_dsname.html',1,'library_dataset']]],
  ['str_5fisgeo',['str_isgeo',['../d0/d1a/sas_str_isgeo.html',1,'library_geog']]],
  ['str_5fisvar',['str_isvar',['../d4/d76/sas_str_isvar.html',1,'library_dataset']]],
  ['str_5fto_5fkeyvalue',['str_to_keyvalue',['../d8/d22/sas_str_to_keyvalue.html',1,'library_struct']]],
  ['str_5ftype',['str_type',['../d0/d76/sas_str_type.html',1,'library_struct']]],
  ['str_5fvarlist',['str_varlist',['../da/d86/sas_str_varlist.html',1,'library_dataset']]],
  ['silc_5fdb_5flocate',['silc_db_locate',['../dd/d51/silc_db_locate.html',1,'Integration']]],
  ['stata_20silc_5fdb_5flocate',['Stata silc_db_locate',['../d3/d36/stata_silc_db_locate.html',1,'silc_db_locate']]],
  ['silc_5fincome_5finventory',['silc_income_inventory',['../d1/d32/stata_silc_income_inventory.html',1,'Estimation']]]
];
